_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1  # only has one class (licenseplate)
DATASETS:
  TRAIN: ("licenseplates_train",)
  TEST: ("licenseplates_test",)
SOLVER:
  BASE_LR: 0.02
  IMS_PER_BATCH: 2
  MAX_ITER: 300  # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
DATALOADER:
  NUM_WORKERS: 2